version: '3'

services:
  astro:
    build: .
    container_name: astro_app
    restart: always
    expose:
      - "80"
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - astro
    networks:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c"
    command: >
      "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done"

networks:
  web:
    driver: bridge
